#11
DeepBaksuVision/Binarized_Neural_Network pull request #14
Opened 2019-11-19 16:44 UTC by Ronalmoo

Merge 해주시면 이어서 BinaryLinear 작성하겠습니다.

2019-11-19 17:29 UTC, ssaru commented on utils/layer.py
> +    print(binarization(example, deterministic=False))
이런 테스트 코드를 짜실 땐, `rand`말고 `randn`으로 하세요
값이 모두 양수가 나와서 음수값을 확인하기 어렵습니다.

제가 직접 테스트 코드를 아래와 같이 작성해서 테스트한 결과 잘 나오네요
```
example = torch.randn(5, 5)
    print("weights")
    print(example)
    print()
    print("prob")
    print(hard_sigmoid(example))
    print("result")
    a = binarization(example, deterministic=False)
    print("output")
    print(a)
    print()
    for i in range(99):
        a += binarization(example, deterministic=False)
    print(a)
```

**결과**
```
weights
tensor([[-0.7316,  0.1605, -0.5484, -0.8392,  0.6781],
        [-0.2401,  2.3644, -0.6030,  0.3593, -0.2727],
        [-0.0120, -0.5060, -1.6718, -0.6257, -1.8605],
        [-0.3098,  0.1641, -1.1046, -1.0734, -0.3668],
        [-0.5970, -1.8555,  1.5306,  0.3630, -0.3066]])

prob
tensor([[ 0.1342,  0.5803,  0.2258,  0.0804,  0.8391],
        [ 0.3800,  1.0000,  0.1985,  0.6796,  0.3637],
        [ 0.4940,  0.2470, -0.3359,  0.1872, -0.4302],
        [ 0.3451,  0.5821, -0.0523, -0.0367,  0.3166],
        [ 0.2015, -0.4278,  1.0000,  0.6815,  0.3467]])
result
output
tensor([[ 1.,  1.,  1.,  1., -1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [-1., -1., -1.,  1.,  1.],
        [-1.,  1.,  1., -1., -1.],
        [ 1., -1.,  1.,  1.,  1.]])

tensor([[ 20.,  62.,  16.,  20.,  86.],
        [ 24., 100.,  30.,  74.,  10.],
        [ 40.,  18., -26.,  18., -48.],
        [ 30.,  62.,   2.,  -6.,  26.],
        [ 26., -36., 100.,  84.,  18.]])
```

2019-11-19 17:30 UTC, ssaru commented on utils/layer.py
> +    print(binarization(example, deterministic=False))
근데 한가지 의아한거는 `hard_sigmoid`에서 min값이 -1로 구현되어있네요.
sigmoid의 범위는 [0, 1]아닌가요?

2019-11-19 17:32 UTC, ssaru commented on utils/layer.py
> +    return clamp
근데 한가지 의아한거는 `hard_sigmoid`에서 min값이 -1로 구현되어있네요.
sigmoid의 범위는 [0, 1]아닌가요?

수정하셔야할 듯 하네요

<img width="1243" alt="Screen Shot 2019-11-20 at 2 31 29 AM" src="https://user-images.githubusercontent.com/13328380/69170725-ec160c80-0b3d-11ea-9bf2-a2a616db8773.png">

2019-11-19 17:36 UTC, ssaru commented on utils/layer.py
> +        # return torch.rand(hard_sigmoid(w).size()).round() * 2 - 1
이건 제 개인적인 코멘트인데, `else`는 되도록 쓰지 마시는게 좋습니다.
습관의 문제인데, 지금 처럼 `deterministic` 아니면 `stochastic`만 존재하는 경우에는 상관없는데
만약 스스로 생각한 조건이 `detecministic`외에 고려하지 못한 조건이 있는데 `else`를 쓰게되면 디버깅이 어려워 질 수 있습니다.

그래서 차라리 습관을 아래와 같은 방법으로 들이시는게 좋습니다.
```
def binarization(w, mode="stochastic"):
    if mode = "deterministic":
        ....
    elif mode = "stochastic":
       ....
    else:
        raise RuntimeError("{} not supported".format(mode))
```

2019-11-19 17:40 UTC, ssaru commented on utils/layer.py
> +        # return torch.rand(hard_sigmoid(w).size()).round() * 2 - 1
추가적으로 `if` `elif`, `else`로 분기하실 거 라면 `deterministic` 함수와 `stochastic`함수를 별도로 분리하시는건 어떠신가요?
이것도 하나 팁인데, 보통 함수에서 추상화 레벨을 맞춰주시면 좋습니다.

가독성이 좋아집니다.

예를들어
```
# 상위 단계의 추상화
def 이진화(x, 모드=스토캐스틱):
    if 모드==스토캐스틱:
        return 스토캐스틱(x)
    elif 모드 == 디터미니스틱:
        return 디터미니스틱:
    else:
        raise 에러
    
   # 하위 단계의 추상화
   def 스토캐스틱(x):
        토치 텐서를 생성한다 어쩌구 저쩌구
        토치 텐서를 슬라이싱 하고 어쩌구 저쩌구
```

2019-11-19 17:43 UTC, ssaru commented on utils/layer.py
> +        # return torch.rand(hard_sigmoid(w).size()).round() * 2 - 1
동적 타입인 파이썬 특성상 시스템이 커졌을 때, 인자의 타입이 굉장히 큰 문제가 됩니다.
항상 type hinting해주세요.

```
def binarization(x:torch.tensor, mode="stochastic": str):
    ....
```

2019-11-19 17:43 UTC, ssaru commented on utils/layer.py
> +        # return torch.rand(hard_sigmoid(w).size()).round() * 2 - 1
이건 첨언입니다.

저도 그렇지만 사람들이 자주하는 실수가 함수 작성시 input type, ouput type, dimension, axis를 고려하지 않고 함수나 클래스 작성하는 것입니다. 그런 경우 잘못 작성해서 다시 작성하는 경우가 있으니 그런 부분 신경써서 작성해주세요

2019-11-19 17:46 UTC, ssaru commented on utils/layer.py
> +    print(binarization(example, deterministic=False))
첨언입니다.

항상 함수 작성 전에 내가 이 로직을 작성하면 어떤 결과가 나와야하는지 부터 고려해서
테스트 코드부터 작성하고 짜는 습관을 들이면 좋을 것 같습니다.

제 마음 같아서는 테스트 주도개발을 하고싶지만, 저도 연습해야하는 부분인지라...

일단은 지금은 `__name__=="__main__"` 형태로라도 코딩 들어가기 전에 테스트 코드를 작성 부탁드리곘습니다.

2019-11-19 17:50 UTC, ssaru requested changes

2019-11-19 17:50 UTC, ssaru commented on utils/layer.py
> +    print(binarization(example, deterministic=False))
코드 리뷰 완료하였습니다.
제가 코멘트 단 부분을 수정하셔서 업데이트 부탁드립니다.

2019-11-20 02:35 UTC, Ronalmoo commented on utils/layer.py
> +    return clamp
헉 음과 양에 심취해 있어서ㅜ 수정하겠습니다

2019-11-20 05:24 UTC, chromatices approved these changes
고생하셨습니다.

2019-11-20 05:24 UTC, chromatices commented on utils/layer.py
> +    return clamp
def hard_sigmoid(x):
    return torch.clamp((x + 1.0) / 2.0, -1, 1)

이런식으로 수정해도 되는지 여쭤봅니다.

2019-11-20 10:04 UTC, ssaru commented on utils/layer.py
> +    clamp = (torch.clamp((x + 1.0) / 2.0, 0, 1))
수정 확인했습니다.

2019-11-20 10:06 UTC, ssaru commented on utils/layer.py
> +    elif "stochastic" in kwargs.values():
만약에 예를들어 `kwargs`가 `["deterministic", "stochastic"]`이면 어떻게 작동하나요?

2019-11-20 10:06 UTC, ssaru commented on utils/layer.py
> +        raise RuntimeError("{} not supported".format(kwargs.values()))
변경사항 확인했습니다.

2019-11-20 10:06 UTC, ssaru commented on utils/layer.py
> +    return clamp
`torch.clamp((x + 1.0) / 2.0, 0, 1)`형태로 하는게 맞습니다.

2019-11-20 14:18 UTC, Ronalmoo commented on utils/layer.py
> +    elif "stochastic" in kwargs.values():
value 값만 영향을 주기 때문에  key 부분은 상관없습니다.

2019-11-20 15:30 UTC, ssaru requested changes

2019-11-20 15:30 UTC, ssaru commented on utils/layer.py
> +    """
Documents string은 Google Documentstring convension을 따라가는게 어떠십니까?

https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2019-11-20 15:30 UTC, ssaru approved these changes

2019-11-20 15:32 UTC, ssaru commented on utils/layer.py
> +    elif "stochastic" in kwargs.values():
제가 말씀드리는 것은 value 2개가 조건문에 모두 포함되기 떄문에 `if`, `elif`에 모두 걸릴 거 같아서 말씀드린거예요
로직이 명확하게 분기가 안될겁니다.

더 정확히 말하면 위에서부터 코드를 리딩하기 때문에 value는 `deterministic`, `stochastic`모두를 포함해서 모든 조건을 만족하지만 `if`에만 걸려서 `deterministic`만 작동하게 됩니다.

2019-11-20 15:37 UTC, ssaru commented on utils/layer.py
> +            print("Binarization: {}".format(binarization))
이 부분은 deterministic이니까 꼭 for문을 100번 돌 필요는 없을 것 같습니다.

2019-11-20 15:43 UTC, ssaru commented on utils/layer.py
>  if __name__ == "__main__":
테스트 코드는 해당 모듈에서 테스트해야하는 모든 테스트를 진행해야합니다.
해당 테스트는 default가 "deterministic"만 고려하여 테스트 코드가 작성되었습니다.

제가 생각했을 때는 아래와 같이 테스트 코드가 짜여지면 더 좋을 것 같습니다.

```
# Test code
# Use parser
example = torch.randn(5, 5)
print("example: {}".format(example))

# detecministic test case
binarization = binarization(example, mode="deterministic")
print("deterministic quantization: {}".format(binarization))

# stochastic test case
prob = hard_sigmoid(example)
print("prob: {}".format(prob))
print(binarization(example, mode="stochastic"))
binarization_sum = binarization(example, mode="stochastic")
print("stochastic quantization: {}".format(binarization_sum))

for i in range(99):
    binarization_sum += binarization(example, mode="stochastic")

print("proof prob in stochastic method: {}".format(binarization_sum))

```

2019-11-20 15:48 UTC, ssaru commented
승무님 branch 파실 때 `issue11`이라는 네이밍의 브랜치를 파셨는데, `feature/#11`형태로 부탁드릴게요!

2019-11-20 16:58 UTC, Ronalmoo commented
정성어린 참교육 감사합니다 마틴님 ㅠ

2019-11-21 06:11 UTC, ssaru requested changes

2019-11-21 06:11 UTC, ssaru commented on utils/layer.py
> +    return  bin_weight
굿

2019-11-21 06:11 UTC, ssaru commented on utils/layer.py
> +    return  bin_weight
근데 `with torch.no_grad()` 어디갔나요......
3번째 말씀드리는 거 같은데.....

2019-11-21 06:11 UTC, ssaru commented on utils/layer.py
> +    return w
`with torch.no_grad()`

2019-11-21 06:11 UTC, ssaru commented on utils/layer.py
> +
굳

2019-11-21 06:11 UTC, ssaru commented on utils/layer.py
>      clamp = (torch.clamp((x + 1.0) / 2.0, 0, 1))
굳

2019-11-21 06:11 UTC, ssaru commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
굿

2019-11-21 06:12 UTC, ssaru commented on utils/layer.py
> +    """
DocString은 생략하셨군요

2019-11-21 11:55 UTC, Ronalmoo commented on utils/layer.py
> +    return  bin_weight
헉.... 넣겠습니당!

2019-11-21 12:43 UTC, ssaru requested changes

2019-11-21 12:43 UTC, ssaru commented on utils/layer.py
> +    return bin_weight
`torch.no_grad()`옵션 비교분석 테스트해보셔요~
그리고 댓글로 남겨주세요~

2019-11-22 02:47 UTC, Ronalmoo commented on utils/layer.py
> +    return bin_weight
<img width="486" alt="스크린샷 2019-11-22 오전 11 44 46" src="https://user-images.githubusercontent.com/44221520/69393927-dd864b80-0d1d-11ea-9b72-0a02b9d26122.png">

2019-11-22 02:50 UTC, Ronalmoo commented on utils/layer.py
> +    return bin_weight
<img width="542" alt="스크린샷 2019-11-22 오전 11 50 02" src="https://user-images.githubusercontent.com/44221520/69394054-39e96b00-0d1e-11ea-9827-720963d90333.png">

2019-11-22 03:01 UTC, Ronalmoo commented on utils/layer.py
> +    """
넵 키워드 아규먼트를 삭제해서 일단은 작성 안했고(컨벤션 보니까 기본 작성을 원칙으로 하긴 하지만 ㅠ)
다시 공부해서 제대로 작성하기 위해서 일단 생략했습니다ㅠ

2019-11-22 08:01 UTC, ssaru requested changes

2019-11-22 08:01 UTC, ssaru commented on utils/layer.py
> +            raise RuntimeError
에러 메세지 안남겨주시면 에러났을 때, 어디서 에러났는지 어떻게 확인하나요?

2019-11-22 08:01 UTC, ssaru commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
이 분도 똑같으시네

제가 말씀드린 것에 대한 의도를 전혀 이해하고 못하는 것 처럼 보이십니다.

벤치마크를 하는 이유는 무엇인가요?
벤치마크를 통해서 무엇을 확인하고 싶은건가요?

    1. 초기 구현하신 Quantization 함수에는 with torch.no_grad()옵션이 구현되어있지 않았습니다.

    2. 저는 with torch.no_grad()를 사용하지 않은 경우 코드 레벨에서 부작용이 발생할 가능성이 있다고 판단했습니다. 그래서 with torch.no_grad()옵션을 붙이라고 조언을 드렸던 것입니다.

    2. 승무님도 단순히 제가 with torch.no_grad()를 붙이는게 좋다고 말씀드려서 with torch.no_grad()옵션을 붙이신 것으로 보였습니다. 이렇게 하면 제가 조언 드리는 이유가 뭐가 되나요? 그냥 아 그렇구나 하고 넘어가나요? 제가 틀렸으면 어떻게 하실겁니까?

    3. 이러한 이유 때문에 Quantization함수에 with torch.no_grad()가 있을 때와 없을 때, input으로 들어간 torch.tensor와 output torch.tensor의 멤버 변수인 torch.tensor.grad torch.tensor.grad_fn의 값이 어떻게 변화하는지 확인보라고 말씀드렸던 것입니다.

    4. 이를 확인하여 Quantization 함수에서 with torch.no_grad()가 있을 때, 없을 때 어떠한 결과가 나오는지 확인해보고 with torch.no_grad()를 사용하고 사용하지 않은 모델을 forward, backward했을 때 어떠한 영향이 올지 생각해보라고 말씀드린 것입니다.

torch.tensor.grad와 torch.tensor.grad_fn의 역활이 무엇입니까?
그 둘은 PyTorch에서 어떻게 사용되나요?

2019-11-22 08:02 UTC, ssaru commented on utils/layer.py
> +    return bin_weight
1. `torch.tensor.grad`와 `torch.tensor.grad_fn`이 어떻게 변하는지 확인해보시구요
2. 그게 무엇을 의미하시는지 적어보시구요
3. `with torch.no_grad()`를 넣고 안넣고가 Quantization에서 어떠한 영향을 끼치고 모델 전체에는 어떻게 영향을 줄 수 있는지 적어보시라구요.

2019-11-22 08:17 UTC, Ronalmoo commented on utils/layer.py
> +    return bin_weight
카톡카톡~~

2019-11-22 08:24 UTC, Ronalmoo commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
모델 구현 단계에서는 당연히 필요하다고 인지 하는데 지금 단계에서 차이점을 확인하고 싶어하시는것 같아서 
별도로 default가 requires=False를 True로 줘서 차이점을 보여드렸습니다. grad_fn도 연산이 진행되어서 clamp가 출력되었고요.
따라서 weight 뽑는 현 단계에서는 with torch.no_grad의 사용유무가 차이점이 없다고 생각합니다.

2019-11-22 08:37 UTC, Ronalmoo commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
제 경우 with torch.no_grad 사용유무의 의미에 대해서 저번 대화때  이해하고  깨달은게 있어서 사용해야 한다는 인식은 있었는데 코드 작성시 부주의로 단순 누락을 한 점이 있었으나, 아무 생각없이 붙이지는 않았습니다.
실제로 해당 모듈에서 굳이 no_grad를 사용해야하는지 문의드렸었고 (모듈을 호출하는 곳에서 지정해주면 되는거 아닌지) 고민과 이해는 있다고 생각합니다.

2019-11-22 09:03 UTC, Ronalmoo commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
추가적으로 주신 생각해볼 것에 관한 답변으로는
각각 quantization method에서 grad랑 grad_fn을  torch.no_grad()했을 때와 안했을 때 어떻게 출력되는지 확인한다.
=> 차이 없음.
 차이를 확인하려면 디폴트로 False가 지정된 torch.tensor(requires_grad=False)에서 True를 주어야 차이가 있음

y = a * a의 연산 이후에 각각 quantization method했을 때, grad랑 grad_fn을  torch.no_grad()했을 때와 안했을 때 어떻게 출력되는지 확인한다.
마찬가지로 torch.no_grad() 옵션이 아니라 requires=True를 주지 않는 이상 차이가 없음
+ 원래 개념으로는 연산 전에는 grad_fn이 None이고 연산 후에는 해당하는 연산+grad_fn이 출력됨

2019-11-22 09:32 UTC, Ronalmoo commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
각각 gradient랑 grad_fn은 결국 미분해주는건데
grad_func은 Activation의 derivate. torch.tensor.require_grad=true를 줘야 순전파시 미분할 거리가 생기는거고 backward할때 미분한 값이 나옵니다.
그 값으로 model.parameter를 업데이트 해주는 방식으로 사용됩니다.

2019-11-22 13:49 UTC, ssaru commented on utils/layer.py
> +    print("After sum Binarizaion: {}".format(binarization_sum))
확인했습니다. 고생하셨어요!
이제 머지 합시다

2019-11-22 13:52 UTC, ssaru approved these changes

2019-11-22 13:52 UTC, merged