Approximate Power-of-2(AP2) 구현
DeepBaksuVision/Binarized_Neural_Network pull request #15
Opened 2019-11-20 06:14 UTC by chromatices

논문에 있는 AP2 함수를 torch전용으로 구현했습니다.

또한 tensor에서 bit shift를 할 수 있도록 함수구현했습니다.

2019-11-20 06:34 UTC, Ronalmoo approved these changes
수고하셨습니다.

2019-11-20 08:19 UTC, ssaru requested changes

2019-11-20 08:19 UTC, ssaru commented on utils/AP2.py
> +    return torch.sign(x) * 2 ** torch.round(torch.log2(torch.abs(x)))
1. 타입 힌팅 해주세요. 

2. x가 `torch.tensor`인데 이렇게 연산하면 gradient를 추적하게 되겠죠? 혹시 모르니, gradient를 연산 안하는 부분은 `with torch.no_grad`를 씁시다

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +        print("Bit shift function needs Tensor. Please transform")
굿!

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +def bit_shift_tensor(tensor):
타입 힌팅해주세요~

2019-11-20 08:19 UTC, ssaru commented on utils/AP2.py
> +def AP2(x):
파이썬에서 함수명은 소문자입니다.
스크립트 파일명도 소문자입니다.

https://medium.com/@kkweon/%ED%8C%8C%EC%9D%B4%EC%8D%AC-doc-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C%EC%97%90-%EB%8C%80%ED%95%9C-%EC%A0%95%EB%A6%AC-b6d27cd0a27c

`approximate_power_of_two`라는 함수명을 쓰시고 실제로 사용하실 땐,
`from ap2 import approximate_power_of_two as AP2`

이렇게 쓰시는게 좋을 것 같습니다.

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +    tensor_np = tensor.numpy()  # reformat cuz bit shift
cuda tensor에서 테스트 해보셨습니까?
작동 안될 거 같은데요? 🤔

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +
AP2함수에서 부호가 마이너스인 경우를 처리하는 로직으로 보이는데
이렇게 for 문을 돌아야하는 이유가 있나요?

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +
아래 코드의 의미가 무엇인가요?
`np.log2(1 + flat_tensor[arr_len])`

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +    flat_bits = np.ones(flat_tensor.shape)  # make numpy array
bit shift를 위한 초기값 설정을 하는 것 같은데 왜 `np.ones`로 초기화하나요?
그러면 아무 shift를 안하는 경우에도 shift를 하게 되지 않을까요?

뒤에 있는 `if, else`가 막아줄 것 같은데, 이러한 상황을 인지하고 있었더라도
이런 형태의 코드는 버그를 만들 수 있지 않을까요?

2019-11-20 08:19 UTC, ssaru commented on utils/bit_shift_tensor.py
> +    print(bit_shift_tensor(a))
이것을 돌렸을 때, 테스트 결과가 어떻게 나오는지 보여주실 수 있나요?

2019-11-20 08:20 UTC, ssaru commented on utils/bit_shift_tensor.py
> +    print(bit_shift_tensor(a))
리뷰 완료하였습니다.
확인 부탁드려요~

2019-11-20 08:29 UTC, chromatices commented on utils/AP2.py
> +    return torch.sign(x) * 2 ** torch.round(torch.log2(torch.abs(x)))
넵 알겠습니다

2019-11-20 08:29 UTC, chromatices commented on utils/bit_shift_tensor.py
> +def bit_shift_tensor(tensor):
넵 ㅎㅎ

2019-11-20 08:30 UTC, chromatices commented on utils/AP2.py
> +def AP2(x):
수정하겠습니다

2019-11-20 08:30 UTC, chromatices commented on utils/bit_shift_tensor.py
> +    tensor_np = tensor.numpy()  # reformat cuz bit shift
cuda를 고려안했습니다 수정하겠습니다

2019-11-20 08:35 UTC, chromatices commented on utils/bit_shift_tensor.py
> +
테스트할때 torch.rand로 진행해서 잘못생각했습니다 수정할게요!

변수에 1을 더한 이유는 변수가 0일경우 -inf으로 출력되기 때문에 이를 방지하고자 처리했습니다.

2019-11-20 08:37 UTC, chromatices commented on utils/bit_shift_tensor.py
> +    flat_bits = np.ones(flat_tensor.shape)  # make numpy array
넵 np.zeors로 초기화하는게 맞습니다. for문으로 연산했을때 이상이 없어서 체크하지 않고 넘어갔습니다 수정할게요

2019-11-20 08:37 UTC, chromatices commented on utils/bit_shift_tensor.py
> +    print(bit_shift_tensor(a))
네 사진첨부하겠습니다

2019-11-20 09:22 UTC, chromatices commented on utils/bit_shift_tensor.py
> +    print(bit_shift_tensor(a))
tensor([[-0.8653, -1.0771,  0.6412],
        [ 0.0735,  1.4614,  0.4467],
        [-1.5455, -1.0573, -1.5968]])
a.type : <class 'torch.Tensor'>
tensor([[-1, -1,  0],
        [ 0,  1,  0],
        [-1, -1, -1]])
bit_shift_tensor.type : <class 'torch.Tensor'>

2019-11-20 09:24 UTC, chromatices commented on utils/bit_shift_tensor.py
> +    print(bit_shift_tensor(a))
``` tensor([[-0.8653, -1.0771,  0.6412],
        [ 0.0735,  1.4614,  0.4467],
        [-1.5455, -1.0573, -1.5968]])
a.type : <class 'torch.Tensor'>
tensor([[-1, -1,  0],
        [ 0,  1,  0],
        [-1, -1, -1]])
bit_shift_tensor.type : <class 'torch.Tensor'> ```

2019-11-20 09:37 UTC, chromatices commented on utils/bit_shift_tensor.py
> +    print(bit_shift_tensor(a))
```python
tensor([[-0.8928, -0.9412,  0.8817],
        [ 0.8969, -0.7678, -1.4526],
        [ 0.1570, -0.0094,  0.4683]])
a.type : <class 'torch.Tensor'>
tensor([[-1, -1,  1],
        [ 1, -1, -1],
        [ 0,  0,  0]])
bit_shift_tensor.type : <class 'torch.Tensor'>
```

2019-11-20 16:18 UTC, ssaru commented on utils/bit_shift_tensor.py
> +
그 때는 엡실론으로 처리하는 겁니다.
1이 아니라 0은 아니지만 0에 가까운 값(파이썬에서 사용할 수 있는 최소 값)
https://stackoverflow.com/questions/9528421/value-for-epsilon-in-python

2019-11-20 16:20 UTC, ssaru commented on utils/bit_shift_tensor.py
> +
제가 잘못이해하고 있는 걸 수도 있지만
아래 AP2 함수에서 `torch.sign(x)`가 부호를 나타내는데 별도로 이렇게 사용하는게 맞는지 궁금해서 여쭈어 본 것입니다. 
```
torch.sign(x) * 2 ** torch.round(torch.log2(torch.abs(x)))
```

제가 잘못 이해하고있다면, 해당 로직의 의도가 무엇인지 전반적으로 리뷰 부탁드리겠습니다.

2019-11-20 16:26 UTC, ssaru requested changes

2019-11-20 16:26 UTC, ssaru commented on utils/bit_shift_tensor.py
> +def bit_shift_tensor(tensor: torch.tensor):
승무님 코드 리뷰에서도 이야기했지만 return value도 type hinting을 할 수 있습니다.
추가해주세요

2019-11-20 16:26 UTC, ssaru commented on utils/bit_shift_tensor.py
> +        raise TypeError("Bit shift function needs Tensor. Please transform")
타입 힌팅이 되어있는 경우 Python에서 해당 타입이 아닌 값을 파라미터로 넣으면 에러를 발생해줄 겁니다.
한번 확인해보세요.

에러가 발생한다면 해당 `raise`는 의미 없을 수 있습니다.

함수에 명확하게 input type과 output type을 명시했음에도 사용자가 다른 타입을 쓴다면
사용자의 실수입니다.

함수나 클래스를 작성할 때, 명시된 타입 힌팅 안에서 의도한 로직을 정확하게 수행하는 정도로만 코드를 작성하면 될 것 같습니다.

2019-11-20 16:26 UTC, ssaru commented on utils/bit_shift_tensor.py
> +        tensor_np = tensor.numpy()          # reformat cuz bit shift
`torch.cuda_is_available()`함수를 사용하지 않고도
그냥 `tensor.cpu().numpy()`라고 작성해버리면 device가 뭐가 들어와도 정확하게 작동하지 않을까요?
실제 로우 레벨에서 값이 cpu에 있는데 cpu()를 호출하면 아무 동작안하고 리턴할 것 같습니다.

이렇게 `if, else`로 분기하게 되면 코드를 읽는데 추가적인 인지 로드가 발생할 것 같습니다.

뭐 큰 상관은 없는데 개인적인 사견입니다.
호불호가 있으니 취향존중!

2019-11-20 16:26 UTC, ssaru commented on utils/bit_shift_tensor.py
>      flat_bits = flat_bits.astype(np.int64)  # remake type
굿! 👍

2019-11-20 16:27 UTC, ssaru commented
branch를 `develop`에서 PR을 하시면 어떻게 합니까
branch 따서 작업 부탁드립니다.

2019-11-20 16:34 UTC, ssaru commented on utils/ap2.py
> +        return torch.sign(x) * 2 ** torch.round(torch.log2(torch.abs(x)))
굿! 👍

2019-11-20 16:35 UTC, chromatices commented on utils/bit_shift_tensor.py
> +        raise TypeError("Bit shift function needs Tensor. Please transform")
기존에 if문에서 raise로 수정한 이유는 Bit shift function needs Tensor. Please transform이 출력되고나서 추가로 기존 파이썬 에러가 발생하기 때문에 깔끔하게 보는편이 좋을듯하여 수정했습니다. 문제시 수정하겠습니다

2019-11-20 16:35 UTC, chromatices commented on utils/bit_shift_tensor.py
> +        tensor_np = tensor.numpy()          # reformat cuz bit shift
아직 사용하는데 미숙해서 그 방법은 생각하지 못했습니다 조언감사합니다!

2019-11-20 16:36 UTC, chromatices commented
> branch를 `develop`에서 PR을 하시면 어떻게 합니까
> 이번엔 패스하시고 다음 부터는 branch 따서 작업 부탁드립니다.
> 
> 현재 프로젝트에서는 그렇게 큰 문제는 아닌데, 습관을 들이는 연습을 하는 겸에서 말씀드립니다.

2019-11-20 16:36 UTC, chromatices commented
> > branch를 `develop`에서 PR을 하시면 어떻게 합니까
> > 이번엔 패스하시고 다음 부터는 branch 따서 작업 부탁드립니다.
> > 현재 프로젝트에서는 그렇게 큰 문제는 아닌데, 습관을 들이는 연습을 하는 겸에서 말씀드립니다.

2019-11-20 16:37 UTC, ssaru commented on utils/ap2.py
> +    print(approximate_power_of_two(torch.randn(3,3)))
input data를 먼저 print찍고 
output data를 print찍읍시다.

전후 결과를 알기 어렵네요

2019-11-20 16:39 UTC, chromatices commented on utils/ap2.py
> +    print(approximate_power_of_two(torch.randn(3,3)))
넵 알겠습니다!

2019-11-20 16:39 UTC, ssaru commented on utils/ap2.py
> +    print(approximate_power_of_two(torch.randn(3,3)))
아래와 같이 코드를 변경하여 확인하였습니다.
```
import torch


def approximate_power_of_two(x: torch.tensor):
    with torch.no_grad():
        return torch.sign(x) * 2 ** torch.round(torch.log2(torch.abs(x)))


if __name__ == "__main__":
    test_tensor = torch.randn((3,3))
    print(test_tensor)
    print(approximate_power_of_two(test_tensor))
```

이렇게 테스트 해본 결과 아래와 같이 출력이 나왔습니다.
AP2함수는 정수로 나와야하는거 아닌가요?
값이 이상한 것 같네요.
```
tensor([[-1.2472, -1.5757,  0.9014],
        [-0.8314, -0.7054,  0.7501],
        [ 0.0821,  0.6221, -0.7495]])
tensor([[-1.0000, -2.0000,  1.0000],
        [-1.0000, -0.5000,  1.0000],
        [ 0.0625,  0.5000, -1.0000]])
```

2019-11-20 16:57 UTC, chromatices commented on utils/bit_shift_tensor.py
> +
입실론에 대해서 검색해봤는데 수학적 정의처럼 엄청 작은 값이고, weight의 경우 입실론보단 큰값일경우 똑같은 오류가 발생할 것 같습니다. 입실론을 써도 -inf이 출력하는것을 볼 수 있었습니다.

```python
>>> import sys
>>> import numpy as np
>>> sys.float_info.epsilon
2.220446049250313e-16

>>>np.log2(sys.float_info.epsilon-0.000000001)
nan
```
또한 log(1) = 0 이기 때문에 ```np.log2(1 + abs(flat_tensor[arr_len]))``` 을 사용했습니다.

torch.sign(x)는 부호를 가져오는 함수는 맞습니다. 다만 log2() 에 그대로 사용할 경우 -inf이 발생합니다. 연산이 가능하게끔 부호는 부호대로 가져오고 해당하는 log값은 그대로 가져오도록  작성했습니다. 제가 이해한 부분을 코드로 첨부하겠습니다.

```python
>>> tensor = torch.randn(3,3)
>>> tensor = approximate_power_of_two(tensor)                                    # calculate AP2
>>> tensor_np = tensor.numpy()                              # reformat cuz bit shift
>>> tensor_np = tensor_np.astype(np.int64)                  # reformat cuz bit shift
>>> tensor_np
array([[ 0, -1, -1],
       [-2, -4,  0],
       [-1,  0, -1]])

>>> flat_tensor = tensor_np.reshape(-1)                     # reshape for every various tensor. Some has 2 by 2 but
>>> flat_bits = np.ones(flat_tensor.shape)                  # make numpy array
>>> flat_bits = flat_bits.astype(np.int64)                  # remake type
>>> for arr_len in range(len(flat_tensor)):                 # calculation log2
...       if flat_tensor[arr_len] < 0:
...           flat_bits[arr_len] = -1 * np.log2(1 + abs(flat_tensor[arr_len]))
...       else:
...           flat_bits[arr_len] = np.log2(1 + flat_tensor[arr_len])

>>> flat_bits
array([ 0, -1, -1, -1, -2,  0, -1,  0, -1])

>>> flat_target = flat_tensor >> flat_bits                  # bit shift
>>> flat_target
array([ 0, -1, -1, -1, -1,  0, -1,  0, -1])
```

2019-11-20 17:25 UTC, ssaru commented on utils/bit_shift_tensor.py
> +
아 2^{n}됬을 때, shift value는 n이라서 이를 가지고 오기 위하여 log를 사용한 코드겠군요.
제가 궁금했던 것은 이러한 내용였습니다.
`2^{n}됬을 때, shift value는 n이라서 이를 가지고 오기 위하여 log를 사용한 코드`
이해되었습니다. 감사합니다.

2019-11-20 17:25 UTC, ssaru commented on utils/bit_shift_tensor.py
> +        raise TypeError("Bit shift function needs Tensor. Please transform")
어떤 에러가 발생하나요?

2019-11-21 03:26 UTC, chromatices commented on utils/bit_shift_tensor.py
> +        raise TypeError("Bit shift function needs Tensor. Please transform")
이전버전으로 실행하면 이런식으로 나옵니다
```python
>>> a = 3
>>> print(a)
3
>>> print("a.type : {}".format(type(a)))
a.type : <class 'int'>

>>> print(bit_shift_tensor(a))
Bit shift function needs Tensor. Please transform
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/Binary_Neural_Network_1/bit_shift_tensor.py", line 44, in <module>
    print(bit_shift_tensor(a))
  File "C:/Users/User/PycharmProjects/Binary_Neural_Network_1/bit_shift_tensor.py", line 11, in bit_shift_tensor
    tensor = tensor.type(torch.cuda.FloatTensor)
AttributeError: 'int' object has no attribute 'type'
```

2019-11-21 03:28 UTC, chromatices commented on utils/bit_shift_tensor.py
> +def bit_shift_tensor(tensor: torch.tensor):
넵 알겠습니다

2019-11-21 06:14 UTC, ssaru commented on utils/bit_shift_tensor.py
> +        raise TypeError("Bit shift function needs Tensor. Please transform")
확인했습니다.

2019-11-21 06:17 UTC, ssaru commented on utils/bit_shift_tensor.py
> +
생각해 봤는데... 아래 로직이 무슨 역활을 하는지 알기 어려우니 함수로 분기하는게 어떨까요?
그리고 for문을 안돌아도 될 것 같은데요...

1. 함수 분기
```
for arr_len in range(len(flat_tensor)):  # calculation log2
        if flat_tensor[arr_len] < 0:
            flat_bits[arr_len] = -1 * np.log2(1 + abs(flat_tensor[arr_len]))
        else:
            flat_bits[arr_len] = np.log2(1 + flat_tensor[arr_len])
```

->
```
def calculate_shift_value(flat_tensor:torch.tensor)->torch.tensor:
    for arr_len in range(len(flat_tensor)):  # calculation log2
        if flat_tensor[arr_len] < 0:
            flat_bits[arr_len] = -1 * np.log2(1 + abs(flat_tensor[arr_len]))
        else:
            flat_bits[arr_len] = np.log2(1 + flat_tensor[arr_len])
```


2. for문 제거
numpy matrix를 응용해서 처리해보는 생각을 해보세요.

2019-11-21 07:01 UTC, chromatices commented on utils/bit_shift_tensor.py
> +
함수 분기는 하는 방향이 좋을거같습니다. 

for문을 제거하는 방법도 찾아서 수정하겠습니다

2019-11-21 14:48 UTC, ssaru approved these changes

2019-11-21 14:48 UTC, merged